// import { Geist, Geist_Mono } from "next/font/google";
import { Raleway } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/navbar.js";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} > */}
      <body className={`${raleway.className}`}>
        <header>
          <h1>EventMix</h1>
        </header>
        <Navbar />
        <main>
          {children}
        </main>
        <footer>
          <p>&copy; 2025 EventMix. Todos los derechos reservados.</p>
        </footer>
      </body>
    </html>
  );
}
